export const SETTING_LIST_REQUEST = 'SETTING_LIST_REQUEST'
export const SETTING_LIST_SUCCESS = 'SETTING_LIST_SUCCESS'
export const SETTING_LIST_FAIL = 'SETTING_LIST_FAIL'

export const SETTING_TODAY_REQUEST = 'SETTING_TODAY_REQUEST'
export const SETTING_TODAY_SUCCESS = 'SETTING_TODAY_SUCCESS'
export const SETTING_TODAY_FAIL = 'SETTING_TODAY_FAIL'

export const SETTING_DETAILS_REQUEST = 'SETTING_DETAILS_REQUEST'
export const SETTING_DETAILS_SUCCESS = 'SETTING_DETAILS_SUCCESS'
export const SETTING_DETAILS_FAIL = 'SETTING_DETAILS_FAIL'

export const SETTING_CREATE_REQUEST = 'SETTING_CREATE_REQUEST'
export const SETTING_CREATE_SUCCESS = 'SETTING_CREATE_SUCCESS'
export const SETTING_CREATE_FAIL = 'SETTING_CREATE_FAIL'
export const SETTING_CREATE_RESET = 'SETTING_CREATE_RESET'

export const SETTING_UPDATE_TARGETS_REQUEST =
	'SETTING_UPDATE_TARGETS_REQUEST'
export const SETTING_UPDATE_TARGETS_SUCCESS =
	'SETTING_UPDATE_TARGETS_SUCCESS'
export const SETTING_UPDATE_TARGETS_FAIL = 'SETTING_UPDATE_TARGETS_FAIL'
export const SETTING_UPDATE_TARGETS_RESET = 'SETTING_UPDATE_TARGETS_RESET'

export const SETTING_UPDATE_FOCUSCT_REQUEST =
	'SETTING_UPDATE_FOCUSCT_REQUEST'
export const SETTING_UPDATE_FOCUSCT_SUCCESS =
	'SETTING_UPDATE_FOCUSCT_SUCCESS'
export const SETTING_UPDATE_FOCUSCT_FAIL = 'SETTING_UPDATE_FOCUSCT_FAIL'
export const SETTING_UPDATE_FOCUSCT_RESET = 'SETTING_UPDATE_FOCUSCT_RESET'

export const SETTING_UPDATE_ROUNDCT_REQUEST =
	'SETTING_UPDATE_ROUNDCT_REQUEST'
export const SETTING_UPDATE_ROUNDCT_SUCCESS =
	'SETTING_UPDATE_ROUNDCT_SUCCESS'
export const SETTING_UPDATE_ROUNDCT_FAIL = 'SETTING_UPDATE_ROUNDCT_FAIL'
export const SETTING_UPDATE_ROUNDCT_RESET = 'SETTING_UPDATE_ROUNDCT_RESET'

export const SETTING_UPDATE_EXERCISECT_REQUEST =
	'SETTING_UPDATE_EXERCISECT_REQUEST'
export const SETTING_UPDATE_EXERCISECT_SUCCESS =
	'SETTING_UPDATE_EXERCISECT_SUCCESS'
export const SETTING_UPDATE_EXERCISECT_FAIL =
	'SETTING_UPDATE_EXERCISECT_FAIL'
export const SETTING_UPDATE_EXERCISECT_RESET =
	'SETTING_UPDATE_EXERCISECT_RESET'
